accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('register/', views.register, name='register'),
    path('<slug:uname>', views.UserProfileView.as_view(), name='profile'),
    path('<int:pk>/edit-profile/', views.UserProfileUpdateView.as_view(), name='edit_profile'),
    path('follow/<slug:user>', login_required(views.followUser), name='follow'),
    path('unfollow/<slug:user>', login_required(views.unfollowUser), name='unfollow'),
	path('trending/developers/', views.TopDevelopers.as_view(), name='top_dev'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

api/urls.py
from django.urls import path
from . import views
urlpatterns = [
	path('', views.OverView.as_view()),
	path('list/user-profile', views.UserProfileListView.as_view()),
	path('list/programming-language', views.ProgrammingLanguageListView.as_view()),
	path('trending/questions/', views.TrendingQuestionListView.as_view()),
	path('trending/developers', views.TrendingDeveloperListView.as_view()),
	path('question/<str:url>/', views.QuestionDetailView.as_view()),
	path('can-login/', views.CanLogin.as_view()),
	path('get-profile/', views.GetUserProfile.as_view()),
	path('get-language/', views.GetLanguage.as_view()),
	path('register/', views.RegisterUser.as_view()),
	path('get-questions/', views.GetQuestionsByUser.as_view()),
]

askadev/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from api.views import get_update
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('django.contrib.auth.urls')),
    path('', include('questions.urls')),
	path('api/', include('api.urls')),
	path('get-update/', get_update),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from PIL import Image
from io import BytesIO
from django.core.files import File
import os, uuid


class ProgrammingLanguage(models.Model):
	language = models.CharField(max_length=256)
	bg_color = models.CharField(max_length=50,default='#000000'); 
	def __str__(self):
		return self.language

	class Meta:
		ordering = ['language']

class UserProfile(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	username = models.CharField(max_length=256)
	bio = models.TextField(max_length=200, help_text='A Short Bio about yourself')
	website = models.URLField(blank=True, null=True)
	profile_picture = models.ImageField(upload_to='static/images/profile_picture', max_length=255, blank=True, default='')
	experience = models.PositiveIntegerField(help_text='Exp. in years')
	languages = models.ManyToManyField(ProgrammingLanguage)
	follows = models.ManyToManyField('UserProfile',blank=True, related_name='following')
	followers = models.ManyToManyField('UserProfile', blank=True)
	points = models.PositiveIntegerField(default=0)
	
	def __str__(self):
		return str(self.user)
	
	def save(self, *args, **kwargs):
		tmpUser = User.objects.get(id=self.user.id)
		self.username = tmpUser.username
		# new_image = compress(self.profile_picture)
		# self.profile_picture = new_image
		super().save(*args, **kwargs)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User

accounts/views.py
from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.http import HttpResponse
from django.views.generic import TemplateView, View, UpdateView, ListView
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from .models import UserProfile,ProgrammingLanguage
from questions.models import Question
from PIL import Image, ImageOps
from django.core.files.base import ContentFile
import base64, secrets, io, os, datetime

class TopDevelopers(ListView):
	model = UserProfile
	template_name = 'accounts/top_developers.html'
	context_object_name = 'developers'

	def get_context_data(self,*args, **kwargs):
		context = super(TopDevelopers, self).get_context_data()
		context['asked_questions'] = Question.objects.filter(user=User.objects.get(username=self.request.user)).count()
		return context

	def get_queryset(self, *args, **kwargs):
		queryset = UserProfile.objects.all().order_by('-points').exclude(points__lte=10)
		return queryset

@csrf_exempt
def followUser(request, user):
	usr = User.objects.filter(username=user)
	rusr = User.objects.filter(username=request.user) 
	if usr.exists() and rusr.exists():
		usr = User.objects.get(username=user)
		rusr = User.objects.get(username=request.user)
		userProfile = UserProfile.objects.filter(user=usr)
		ruser = UserProfile.objects.filter(user=rusr)
		if userProfile.exists() and ruser.exists():
			usr = User.objects.get(username=user)
			rusr = User.objects.get(username=request.user)
			userProfile = UserProfile.objects.get(user=usr)
			ruser = UserProfile.objects.get(user=rusr)
			ruser.follows.add(userProfile)
			ruser.save()
			userProfile.followers.add(ruser)
			userProfile.save()
		else:
			return HttpResponse("User Profile Does Not Exist")
	else:
		return HttpResponse("User Does Not Exist")
	return HttpResponse(ruser.follows.all())

@csrf_exempt
def unfollowUser(request, user):
	usr = User.objects.filter(username=user)
	rusr = User.objects.filter(username=request.user) 
	if usr.exists() and rusr.exists():
		usr = User.objects.get(username=user)
		rusr = User.objects.get(username=request.user)
		userProfile = UserProfile.objects.filter(user=usr)
		ruser = UserProfile.objects.filter(user=rusr)
		if userProfile.exists() and ruser.exists():
			usr = User.objects.get(username=user)
			rusr = User.objects.get(username=request.user)
			userProfile = UserProfile.objects.get(user=usr)
			ruser = UserProfile.objects.get(user=rusr)
			ruser.follows.remove(userProfile)
			ruser.save()
			userProfile.followers.remove(ruser)
			userProfile.save()
		else:
			return HttpResponse("User Profile Does Not Exist")
	else:
		return HttpResponse("User Does Not Exist")
	return HttpResponse(ruser.follows.all())

def get_image_from_data_url( data_url, resize=True, base_width=600 ):
    _format, _dataurl       = data_url.split(';base64,')
    _filename, _extension   = secrets.token_hex(20), _format.split('/')[-1]
    file = ContentFile(base64.b64decode(_dataurl), name=f"{_filename}.{_extension}")
    if resize:
        image = Image.open(file)
        image_io = io.BytesIO()
        w_percent = (base_width/float(image.size[0]))
        h_size = int((float(image.size[1])*float(w_percent)))
        image = image.resize((base_width,h_size), Image.ANTIALIAS)
        image.save(image_io, format=_extension)
        file = ContentFile( image_io.getvalue(), name=f"{_filename}.{_extension}" )
    return file, ( _filename, _extension )

class HomePage(TemplateView):
	template_name = 'accounts/home.html'

	def get_context_data(self, *args, **kwargs):
		context = super(HomePage, self).get_context_data(*args,**kwargs)
		if self.request.user.is_authenticated:
			user = User.objects.get(username=self.request.user.username)
			qs = Question.objects.filter(user=user).order_by('-asked_on')
			context['q_list'] = qs
			last_login = user.last_login
			date_joined = user.date_joined
			check_last_login = last_login - date_joined
			if check_last_login < datetime.timedelta(seconds=10):
				context['first_login'] = True
			return context
def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            u = User.objects.get(username=username)
            up = UserProfile(
				user=user,
				bio="",
				website=None,
				experience=1,	
				profile_picture=f'static/images/profile_picture/default.jpg'			
			)
            up.save()
            up.languages.add(ProgrammingLanguage.objects.get(language='C'))
            up.follows.add(UserProfile.objects.get(user=User.objects.get(username='AskaDev')))
            admin = UserProfile.objects.get(user=User.objects.get(username='AskaDev'))
            up.save()
            admin.followers.add(up)
            admin.save()
            return redirect(f'/{u.id}/edit-profile')
    else:
        form = UserCreationForm()
    return render(request, 'registration/register.html', {'form': form})

class UserProfileView(View):
	template_name = 'accounts/user_profile.html'
	def get(self,request, uname, *args, **kwargs):
		get_object_or_404(User, username=uname)
		u = UserProfile.objects.filter(
			user=User.objects.get(username=uname)
		)
		q = Question.objects.filter(
			user=User.objects.get(username=uname)
			).order_by('-asked_on')
		if u.exists():
			user = UserProfile.objects.get(user=User.objects.get(username=uname))
			rusr = get_object_or_404(User, username=request.user.username)
			ruser = get_object_or_404(UserProfile, user=rusr)
			u = u[0]
			if user == ruser:
				sameUser = True
			else:
				sameUser = False
			if user in ruser.follows.all():
				print("Following")
				canFollow = False
				following = "true"
				text = "Following"
			else:
				print("Not following")
				canFollow = True
				following = "false"
				text = "Follow"
			if user in ruser.followers.all() and user not in ruser.following.all():
				canFollow = True
				following = "false"
				text = "Follow Back"
			context = {"canFollow":canFollow,
	 				"sameUser":sameUser,
					"following":following,
					"text":text,
					"profile":u,
					'questions':q
			}
			return render(request, self.template_name, context)
		else:
			return HttpResponse('User Does not Exist')

class UserProfileUpdateView(UpdateView):
	model = UserProfile
	fields = ['experience',
			 'languages',
			 'bio',
			 'website'
	]
	def get(self,request, *args, **kwargs):
		user = User.objects.get(username=self.request.user)
		requested_user = UserProfile.objects.filter(id=self.kwargs['pk'])
		if requested_user.exists():
			if not user==requested_user[0].user:
				return redirect('/')
			else:
				return super(UserProfileUpdateView, self).get(request,*args,**kwargs) 
		else:
			return HttpResponse("Requested Profile Doesn't Exist")
		

	def form_valid(self, form):
		redirect_url = super(UserProfileUpdateView, self).form_valid(form)
		pp_url = self.request.POST.get('pp_url')
		try:
			img = get_image_from_data_url(pp_url)[0]
			form.instance.profile_picture = img
			form.instance.save()
			return redirect_url
		except ValueError:
			form.save()
			return redirect_url

	def get_success_url(self):
		return reverse('profile', args=[str(self.request.user)])

	def get_context_data(self,*args,**kwargs):
		context = super().get_context_data(*args, **kwargs)
		up = UserProfile.objects.get(id=self.kwargs['pk'])
		context['profile'] = up
		im = up.profile_picture.read()
		bs64_url = base64.b64encode(im)
		context['c_pp_url'] = bs64_url.decode()
		return context

templates/accounts/home.html
{% extends "base.html" %}
{% block body %}
{% if request.user.is_authenticated %}
<div id="app-home" >
	{% for i in q_list %}
	<div class="card mx-auto" style="max-width: 1100px;">
		<div class="card-body">
		  <h4 class="card-title font-weight-bold">{{i.title}}</h4>
		  <h4><i class="bx bxs-heart" style="color: rgba(var(--vs-danger));"></i><span style="margin-top: -1.5px;margin-left:3px;position: absolute;">{{i.likes}} Likes</span></h4>
		  <hr class="my-4">
		  <p class="lead">
			  <span style="position: absolute;">By</span>
			  <vs-button
			  href="/{{i.user}}"
			  :style="{marginTop: '0px',marginLeft: '25px',fontSize: '18px',display: 'inline-block'}" transparent size="mini">
				<i class="bx bx-user"></i>&nbsp;{{i.user}}
			</vs-button>
			<span style="position: absolute;">on {{i.asked_on.date}}</span>
		</p>
		<vs-button href="/{{i.user}}/questions/{{i.url}}" :style="{fontSize: '18px'}" size="small">
			View Question
		</vs-button>
		</div>
	  </div>
	  <p></p>
	{% empty %}
	<h4>No Questions Asked</h4>
	<vs-button danger filled size="large" href="/questions/create">
		Ask a Question
	</vs-button>
	{% endfor %}
	<br/>
</div>
{% else %}
<div id="app-home">
<h2>AskaDeveloper 👨‍💻</h2>
<h3>Get your questions🤔 answered by Developers</h3>
<hr>
<h4 id="why_askadev"><a
	style="text-decoration: none;"
	href="#why_askadev">#</a>  Why AskaDev?</h4>
<ul>
	<li>Ask your queries and get solutions from other developers.🤝</li>
	<li>I hope this may benefit you.🙏</li>
	<li>This website is only for programmers.👨‍💻</li>
</ul>
<hr>
<h4 id="tech_used"><a href="#tech_used">#</a> Technologies Used 💻</h4>
<ul>
	<li>HTML</li>
	<li>CSS and Bootstrap</li>
	<li>JavaScript and jQuery + select2 at some places</li>
	<li>Django(Python)</li>
	<li>Twemoji For Emoji Rendering</li>
	<li>Converting Images to Base64 URL.</li>
</ul>
<hr>
<h4 id="ideas"><a href="#ideas" style="text-decoration: none;">#</a> Got Any Ideas 💻</h4>
<ul>
	<li>DM me on Instagram @simplified.web🗨️</li>
	<li>Email me 📧</li>
</ul>
<hr>
<p></p>
<p></p>
<div class="text-center  d-flex justify-content-center">
	<div class="row" style="max-width: 200px;">
		<vs-row vs-w="12">
			<vs-col vs-type="flex" vs-justify="center" vs-align="center" vs-lg="6" vs-sm="12" vs-xs="12" >
				<vs-button size="large" block danger filled href="/login/">
					Login
					<template #animate>
                        <i class="bx bxs-log-in"></i>
                    </template>
				</vs-button>
			</vs-col>
			<vs-col vs-type="flex" vs-justify="center" vs-align="center" vs-lg="6" vs-sm="12" vs-xs="12">
				<vs-button danger transparent href="/register/" block size="large">
					Register
					<template #animate>
                        <i class="bx bxs-user-plus"></i>
                    </template>
				</vs-button>
			</vs-col>
			<vs-col vs-type="flex" vs-justify="center" vs-align="center" vs-lg="6" vs-sm="12" vs-xs="12">
				<h5 class="text-center"><span>Help Us Improve this Website</span></h5>
				<vs-button gradient warn href="https://github.com/Dev-Mehta/AskaDev/issues/new?title=[Bug]%20-%20Bug%20Title&body=**Steps%20to%20Reproduce**%0A1.%20Do%20something%0A2.%20Do%20something%20else.%0A3.%20Do%20one%20last%20thing.%0A%0A**Expected**%0AThe%20app%20should%20do%20this%0A%0A**Result**%0AThe%20Bapp%20does%20not%20do%20this%0A%0A**Testcase**%0A(fork%20this%20to%20get%20started)%0Ahttp://jsfiddle.net/exmple-bug/1/&assignee=Dev-Mehta&labels=bug" blank block size="large">
					Report a Bug
					<template #animate>
					    <i class='bx bxs-bug'></i>
                    </template>
				</vs-button>
			</vs-col>
		  </vs-row>
	</div>
</div>
<p></p>
</div>
{% endif %}
{% endblock body %}
{% block script %}
{% if first_login %}
<script>
	const app_home = new Vue({
	el: '#app-home',
	data: {
		width: '100px',
	},
	delimitors: ['[[', ']]'],
	mounted(){
		const noti = this.$vs.notification({
			sticky: true,
			width: 'auto',
			duration: 'none',
			position: 'bottom-center',
			color: '#7d33ff',
			icon: `<img 
						draggable="false"
						style="width: 1.4rem"
						alt="👋"
						src="https://github.githubassets.com/images/icons/emoji/unicode/1f44b.png">`,
			title: `<p style="font-size:16px;">
					Welcome to AskaDeveloper</p>
					<hr style="border-top: 1px solid #fff">`,
			text: `
			<p style="font-size: 14px;">
					Here you can get answers of your questions.<br/><br/>
					From the top navbar select Ask a Question Button to ask a question.
					You can view trending questions from trending questions page.<br/><br/>
					We  are constantly working to improve this website. You can find more
					about this project on our github repository<br/><br/>
					<a href="https://github.com/Dev-Mehta/AskaDev" 
						target="_blank"
						style="color: #fff; text-decoration: none;">
						<i class='bx bxl-github'></i>
					</a>
			</p>`
		  })
	}
});
</script>
{% else %}
<script>
	const app_home = new Vue({
	el: '#app-home',
	data: {
		width: '100px',
	},
	delimitors: ['[[', ']]'],
});
</script>
{% endif %}

{% endblock %}

templates/accounts/top_developers.html
{% extends 'base.html' %}
{% block body %}
<style>
.card{
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  max-width: 600px;
  margin: auto;
}
.card-image{
	width: 60px;
	border-radius: 50%;
	margin: 0.75rem;
	text-align: left;
}
.title {
	padding: 0.75rem;
	text-align: justify;
	font-size: 18px;
}

.card-btn {
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: white;
  background-color: var(--danger);
  text-align: center;
  cursor: pointer;
  width: 100%;
  font-size: 18px;
  position: absolute;
  margin-top: -20px;
}

.card-btn:hover{
  background: #c12837;
  color: #fff;
  text-decoration: none;
}
</style>
{% for dev in developers %}
<span>&nbsp;</span>
<div class="card">
		<h4>
			<img class="card-image" src="{{dev.profile_picture.url}}" alt="{{ dev.user }}">
			 <span>{{ dev.user }}</span>
		</h4>
		<div class="row" style="text-align: center;">
			<div class="col-4">
				Asked Questions
			</div>
			<div class="col-4">
				Followers
			</div>
			<div class="col-4">
				Following
			</div>
		</div>
		<div class="row" style="text-align: center;">
			<div class="col-4">
				{{asked_questions}}
			</div>
			<div class="col-4">
				{{dev.followers.all.count}}
			</div>
			<div class="col-4">
				{{dev.follows.all.count}}
			</div>
		</div>
	<div class="title">
			{{dev.bio|linebreaks|safe}}
	</div>
	<p><a class="card-btn" href="/{{dev.user}}">Visit Profile</a></p>
  	</div>  
  <spn>&nbsp;</span>
{% endfor %}
{% endblock %}

templates/accounts/user_profile.html
{% extends "base.html" %}
{% load static %}
{% block body %}
<style type="text/css">
	.follow-btn, .follow-btn:focus{
		background: white;
		border: 2px solid rgba(var(--vs-danger));
		color: rgba(var(--vs-danger));
		padding: 4.5px 16px;
		border-radius: 8px;
		transition: 0.3s;
		outline: 0;
	}
	.follow-btn:hover{
		background: rgba(var(--vs-danger));
		color: white;
		text-decoration: none;
	}
	.following-btn, .following-btn:focus{
		background: rgba(var(--vs-danger));
		border: 2px solid rgba(var(--vs-danger));
		color: white;
		padding: 4.5px 16px;
		border-radius: 8px;
		transition: 0.3s;
		outline: 0;
	}
	.following-btn:hover{
		background: white;
		color: rgba(var(--vs-danger));
		text-decoration: none;
	}
	.table thead th, .table td{
		border: none;
		padding: 2px;
		vertical-align: top;
	}
	.badge{
		padding: 4px 18px;
		font-size: 16px;
		margin: 2px;
	}
	.skills{
		margin-top: 2rem;
	}
	.skills p{
		margin-bottom: 5px;
		font-size: 24px;
	}
	.active-pp{
		width: 14px;
		height: 14px;
		margin-top: -2px;
		margin-left: -15px;
		border-radius: 50%;
		position: absolute;
		background-color: #11e743;
		display: inline-block;
	}
</style>
<div id="app_profile">
<div class="container">
		<h4 id="profile_picture" style="
		display: flex">
			<vs-avatar badge badge-position="top-right" badge-color="#11e743" size="large" color="primary">
				<img src="{{profile.profile_picture.url}}" alt="">
			</vs-avatar>
			<span class="ml-2 mt-2">{{ profile.user }}</span></h4>
		<span class="float-right" style="margin-top: -48px;">
			{% if sameUser %}
				<vs-button 
				href="/{{profile.user.id}}/edit-profile"
				color="danger"
				v-bind:style="{fontSize: '14px', border: 'none', fontWeight: '700',outline: 'none'}"
				size="small"
				type="border"
				v-on:click="message = 'Redirecting'"
				>
					[[message]]
				</vs-button>	
			{% else %}
					<button v-bind:class="this.class" @click="followUser" id="follow_btn">[[follow_message]]</button>    	
			{% endif %}
		</span>
		<div class="bio" style="max-width: 400px;">
		<h6 style="font-size: 24px;margin-top: 1rem">Bio</h6>
		<span id="bio">
		{{ profile.bio | linebreaks }}
		{% if profile.website %}
		<a target="_blank" style="margin-top: -20px;position: absolute;" href="{{profile.website}}">{{ profile.website }}</a>
		{% endif %}
		</span>
		</div>
		<div class="skills">
			<p>Languages</p>
			{% for l in profile.languages.all %}
			<!-- <vs-chip color="{{l.bg_color}}" type="filled">
				{{l}}
			</vs-chip> -->
			<div class="badge badge-pill" style="background-color: {{l.bg_color}}; color: #fff;">{{l}}</div>
			{% endfor %}
		</div>
		<br/>
		<p></p>
		<table class="table text-center">
			<thead>
				<th style="width: 33vw;"class="text-center" >Questions Asked</th>
				<th style="width: 33vw;"class="text-center" ><span id="followers">Followers</span></th>
				<th style="width: 33vw;"class="text-center" ><span id="following">Following</span></th>
			</thead>
			<tr class="col">
				<td>{{questions.count}}</td>
				<td id="followers_count">{{profile.followers.count}}</td>
				<td>{{profile.follows.count}}</td>
			</tr>
		</table>
</div>

<hr style="border: 1px solid var(--red);margin-top: 3px;">
<div class="container">
	{% if sameUser %}
	<h3>Your Questions</h3>
	{% else %}
	<h3>{{profile.user}}'s Questions</h3>
	{%  endif %}
	{% for i in questions %}
	<div class="card mx-auto" style="max-width: 1100px;">
		<div class="card-body">
		  <h4 class="card-title font-weight-bold">{{i.title}}</h4>
		  <h4><i class="bx bxs-heart" style="color: rgba(var(--vs-danger));"></i><span style="margin-top: -1.5px;margin-left:3px;position: absolute;">{{i.likes}} Likes</span></h4>
		  <hr class="my-4">
		  <p class="lead">
			  <span style="position: absolute;">By</span>
			  <vs-button 
			  href="/{{i.user}}"
			  :style="{marginTop: '0px',marginLeft: '25px',fontSize: '18px',display: 'inline-block'}" transparent size="mini">
				<i class="bx bx-user"></i>&nbsp;{{i.user}}
			</vs-button>
			<span style="position: absolute;">{{i.asked_on}}</span>
		</p>
		<vs-button href="/{{i.user}}/questions/{{i.url}}" :style="{fontSize: '18px'}" size="small">
			View Question
		</vs-button>
		</div>
	  </div>
	  <p></p>
		{% empty %}
			<h4>No Questions Asked</h4>
		{% endfor %}
</div>
</div>
<script type="text/javascript">
</script>
{% endblock %}
{% block script %}
<script>
const app_profile = new Vue({
	el: '#app_profile',
	delimiters: ['[[',']]'],
	data: {
		'message': 'Edit Profile',
		'following' : {{following}},
		'follow_message': "",
		'class': "",
		'follow_btn':document.querySelector('#follow_btn')
	},
	methods: {
		followUser: function(){
			if(this.following){
				// Unfollow
				this.follow_btn.disabled = true;
				axios.post(
					"/unfollow/{{profile.user}}",
					{"user":"{{profile.user}}"}
				).then((res) =>{
					var f_count = document.querySelector('#followers_count');
					f_count.innerText = parseInt(f_count.innerText) - 1;
					document.querySelector('#follow_btn').disabled = false;
				}).then((err) => {
					if (err !== undefined)alert(err);
				})
				this.following = false;
				this.follow_message = "Follow"
				this.class = "follow-btn"
			}
			else{
				document.querySelector("#follow_btn").disabled = true;
				axios.post(
					"/follow/{{profile.user}}",
					{"user":"{{profile.user}}"}
				).then((res) =>{
					var f_count = document.querySelector('#followers_count');
					f_count.innerText = parseInt(f_count.innerText) + 1;
					document.querySelector('#follow_btn').disabled = false;
				}).then((err)=>{
					if(err !== undefined) alert(err);
				})
				this.following = true;
				this.follow_message = "Following"
				this.class = 'following-btn'
			}
		}
	}
})
window.onload =  function(){
	let following = {{following}};
	if(following){
		app_profile.follow_message = "Following";
		app_profile.class = "following-btn";
	}
	else{
		app_profile.follow_message = "Follow"
		app_profile.class = "follow-btn"
	}
	twemoji.parse(document.body);
		var x = document.querySelectorAll('.emoji');
		for(let i=0;i<x.length;i++){
			const y = x[i];
			y.style.width = "1em"
			y.style.marginLeft = "3px";
			var str = y.src;
  			var res = str.replace("https://twemoji.maxcdn.com/v/13.0.1/72x72/", "https://github.githubassets.com/images/icons/emoji/unicode/");
			y.src = res;
		}
}
</script>
{% endblock %}

templates/accounts/userprofile_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block body %}
<style type="text/css">
	form{
		max-width: 600px;
	}
	textarea{
		max-height: 120px;
	}
</style>
<center>
	<input form="nullform" type="file" id="id_profile_picture" accept="image/*">
    <form class="form-group" method="POST">
    	<br/>
    	<h6 style="font-size: 16px;">Profile Picture</h6>
    	<img class="img-fluid" style="width: 50px;height: 50px;border-radius: 50%;margin-top: 0px;cursor: pointer;" src="{{profile.profile_picture.url}}" id="file_btn">
    	<p id="selected"></p>
    	<input type="hidden" id="pp_url" name="pp_url" value="">
    	{{form.bio|as_crispy_field}}
    	{{form.website|as_crispy_field}}
    	{{form.experience|as_crispy_field}}
    	{{form.languages|as_crispy_field}}
    	{% csrf_token %}
    	<button class="btn btn-block btn-form-submit btn-danger">Submit</button>
    </form>
</center>
{% endblock body %}
{% block script %}
    <script type="text/javascript">
    	$(document).ready(function(){
    		$('#id_languages').select2();
    	})
    	const bs64 = 'data:image/png;base64,'+'{{c_pp_url}}';
    	const compress = function(e) {
			const btn = document.querySelector('.btn-form-submit');
			btn.disabled = true;
		    const width = 800;
		    const height = 800;
		    const fileName = e.target.files[0].name;
		    const reader = new FileReader();
		    reader.readAsDataURL(e.target.files[0]);
		    reader.onload = event => {
		        const img = new Image();
		        img.src = event.target.result;
		        img.onload = () => {
		                const elem = document.createElement('canvas');
		                const pp_url = document.querySelector('#pp_url');
		                elem.width = width;
		                elem.height = height;
		                const ctx = elem.getContext('2d');
		                ctx.drawImage(img, 0, 0, width, height);
		                ctx.canvas.toBlob((blob) => {
		                    const file = new File([blob], fileName, {
		                        type: 'image/jpeg',
		                        lastModified: Date.now()
		                    });
		                }, 'image/jpeg', 0.92);
		                pp_url.append(elem)
		                pp_url.value = elem.toDataURL();
		                document.querySelector("#file_btn").src = elem.toDataURL();
		                btn.disabled = false;
		            },
		            reader.onerror = error => console.log(error);
		    };
		}
    	document.querySelector('#id_profile_picture').required = false
		document.querySelector("#file_btn").onclick = function(){
			document.querySelector('#id_profile_picture').click();
		}
		document.querySelector('#id_profile_picture').onchange = function(){
			document.querySelector('#selected').innerHTML = "Selected " + document.querySelector('#id_profile_picture').files[0].name
			compress(event);
		}
		document.querySelector('#id_profile_picture').style.display='none';

    </script>
{% endblock script %}