api/urls.py
from django.urls import path
from . import views
urlpatterns = [
	path('', views.OverView.as_view()),
	path('list/user-profile', views.UserProfileListView.as_view()),
	path('list/programming-language', views.ProgrammingLanguageListView.as_view()),
	path('trending/questions/', views.TrendingQuestionListView.as_view()),
	path('trending/developers', views.TrendingDeveloperListView.as_view()),
	path('question/<str:url>/', views.QuestionDetailView.as_view()),
	path('can-login/', views.CanLogin.as_view()),
	path('get-profile/', views.GetUserProfile.as_view()),
	path('get-language/', views.GetLanguage.as_view()),
	path('register/', views.RegisterUser.as_view()),
	path('get-questions/', views.GetQuestionsByUser.as_view()),
]

askadev/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from api.views import get_update
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('django.contrib.auth.urls')),
    path('', include('questions.urls')),
	path('api/', include('api.urls')),
	path('get-update/', get_update),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

questions/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.views.static import serve
urlpatterns = [
    path('<slug:user>/questions/<slug:question>/', views.QuestionDetailView, name='question_detail'),
    path('questions/create/', views.QuestionCreateView.as_view(), name='create_question'),
    path('answer/<slug:question>/', views.AnswerCreateView.as_view(),name='answer'),
    path('trending/questions/', views.TrendingQuestionView.as_view(), name='trending'),
	path('like/', views.likePost, name='like_question'),
	path('like/answer/', views.likeAnswer, name='like_answer')
]

if not settings.DEBUG:
    urlpatterns += [
        re_path(r'^uploads/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
        re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    ]

questions/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.utils import timezone
import secrets
class Tags(models.Model):
	tag = models.CharField(max_length=255)
	bg_color = models.CharField(max_length=12)
	def __str__(self):
		return str(self.tag)

	class Meta:
		db_table = 'Tag'
class Question(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	title = models.CharField(max_length=100)
	question = models.TextField()
	tags = models.ManyToManyField(Tags)
	url = models.CharField(max_length=32)
	asked_on = models.DateTimeField(default=timezone.now)
	answers = models.IntegerField(default=0)
	likes = models.IntegerField(default=0)

class Answer(models.Model):
	answered_by = models.ForeignKey(User,on_delete=models.CASCADE)
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	answer = models.TextField()
	url = models.CharField(max_length=32)
	answered_at = models.DateTimeField(default=timezone.now)
	likes = models.IntegerField(default=0)

class AnswerLiker(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
	liked = models.BooleanField(default=False)

class Liker(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	liked = models.BooleanField(default=False)

questions/views.py
from django.shortcuts import render, get_object_or_404, redirect, get_list_or_404
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.views.generic import CreateView, ListView
from accounts.models import UserProfile
from .models import Question, Answer, Liker, AnswerLiker
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
import secrets, json, requests

def gitHubPost(text, mode='markdown'):
	payload = {'text': text, 'mode':mode}
	r = requests.post('https://api.github.com/markdown', data=json.dumps(payload))
	if r.status_code == 200:
		return r.content
	else:
		return None

@csrf_exempt
def likeAnswer(request):
	if request.method == 'POST':
		post = request.POST.get('answer')
		user = request.POST.get('user')
		liked = AnswerLiker.objects.filter(
			user=User.objects.get(username=user),
			Answer=Answer.objects.get(url=post)
		).exists()
		if not liked:
			l = AnswerLiker(
				user=User.objects.get(username=user),
				answer=Answer.objects.get(url=post),
				liked=True
			)
			l.save()
			p = Answer.objects.get(url=post)
			p.likes += 1
			p.save()
		else:
			l = AnswerLiker.objects.get(user=User.objects.get(username=user),question=Question.objects.get(url=post))
			l.delete()
			p = Answer.objects.get(url=post)
			p.likes -= 1
			p.save()
		return HttpResponse(liked)
	else:
		return redirect('/')
@csrf_exempt
def likePost(request):
	if request.method == 'POST':
		js = json.loads(request.body.decode("utf-8"))
		post = js['question']
		user = js['user']
		print(js)
		print(user)
		print(post)
		liked = Liker.objects.filter(
			user=User.objects.get(username=user),
			question=Question.objects.get(url=post)
		).exists()
		if not liked:
			l = Liker(
				user=User.objects.get(username=user),
				question=Question.objects.get(url=post),
				liked=True
			)
			l.save()
			p = Question.objects.get(url=post)
			p.likes += 1
			asked_by = Question.objects.get(url=post).user
			up = UserProfile.objects.get(user=asked_by)
			up.points += 1
			up.save()
			p.save()
		else:
			l = Liker.objects.get(user=User.objects.get(username=user),question=Question.objects.get(url=post))
			l.delete()
			p = Question.objects.get(url=post)
			p.likes -= 1
			asked_by = Question.objects.get(url=post).user
			up = UserProfile.objects.get(user=asked_by)
			up.points -= 1
			up.save()
			p.save()
		return HttpResponse(liked)
	else:
		return redirect('/')
def QuestionDetailView(request, user, question):
	user = get_object_or_404(User, username=user)
	question = get_object_or_404(Question,user=user, url=question)
	user = question.user
	user_profile = UserProfile.objects.get(user=user)
	context = {"user":user, "question":question}
	answers = Answer.objects.filter(question=question).order_by('-answered_at')
	context['answers'] = answers
	liked = Liker.objects.filter(user=User.objects.get(username=request.user),question=question).exists()
	print(liked)
	context['liked'] = liked
	context['user_profile'] = user_profile.profile_picture.url
	return render(request, "questions/question_detail.html",context=context )

class QuestionCreateView(CreateView):
	model = Question
	fields = ('title','question','tags')
	success_url = ''
	def form_valid(self,form):
		tags = form.cleaned_data.get('tags')
		user=User.objects.get(username=self.request.user.username)
		question = form.cleaned_data.get('question')
		md_question = str(gitHubPost(question).decode('utf-8'))
		q = Question(
			user=User.objects.get(username=self.request.user.username),
			title=form.cleaned_data.get('title'),
			question=md_question,
			url=secrets.token_hex(20)
		)
		q.save()
		for i in tags.iterator():
			q.tags.add(i)
		q.save()
		return redirect(f'/{user}/questions/{q.url}')

class AnswerCreateView(CreateView):
	model = Answer
	fields = ('answer',)

	def form_valid(self, form):
		answer = form.cleaned_data.get('answer')
		answer = str(gitHubPost(answer).decode("utf-8"))
		user=User.objects.get(username=self.request.user.username)
		user_profile = UserProfile.objects.get(user=user)
		question = get_object_or_404(Question,url=self.kwargs['question'])
		a = Answer(
			question=question,
			answered_by=user,
			url=secrets.token_hex(20),
			answer=answer,
		)
		a.save()
		user_profile.points += 1
		user_profile.save()
		slug = question.url
		return redirect(f'/{question.user}/questions/{slug}')

class TrendingQuestionView(ListView):
	model = Question

	def get_queryset(self, *args, **kwargs):
		qs = Question.objects.all().order_by('-likes')[:30]
		return qs

templates/questions/answer_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<form method="POST" class="form-group">
    {{form|crispy}}
    {% csrf_token %}
    <input type="submit" class="btn btn-primary" value="Answer">
</form>
{% endblock %}
{% block script %}
<script>
     const md = new SimpleMDE({
        element: document.querySelector('#id_answer'),
    })
    document.querySelector('#id_answer').required = "";
    document.querySelector(".CodeMirror").style.textAlign = "left";
    document.querySelector(".editor-preview-side").style.textAlign = "left";
</script>
{% endblock %}

templates/questions/question_detail.html
{% extends 'base.html' %}
{% load markdown_deux_tags %}
{% block body %}
<style>
    .like-btn, .like-btn:focus{
        background: transparent;
        border: none;
        outline: 0;
    }
	li{
		position: relative;
		margin-left: 20px;
	}
	.highlight{
		font-weight: 400;
	}
</style>
<div id="app_detail">
<div class="container">
	<div class="card mx-auto" style="max-width: 1100px;">
		<div class="card-body">
		  <h4 class="card-title font-weight-bold m-0">{{question.title}}</h4>
		  <div style="font-size: 24px;">
			{% if liked %} 
					<button v-on:click="likeQuestion" class="like-btn" id="addLike">
						<i class="bx bxs-heart"  style="font-size: 1.5rem;color:rgba(var(--vs-danger)); margin-top: -10px;"></i>
					</button>
					{% else %}
					<button v-on:click="likeQuestion" class="like-btn" id="addLike">
						<i class="bx bx-heart" style="font-size: 1.5rem;color:rgba(var(--vs-danger));margin-top: -5px;"></i>
					</button>
					{% endif %}
			<span style="position:absolute">
				{% ifequal question.likes 1 %}
					<span id="likes_count">{{ question.likes }}</span><span> Like</span>
				{% else %}
					<span id="likes_count">{{ question.likes }}</span><span> Likes</span>
				{% endifequal %}
			</span> 
		  <hr class="m-2">
		  <p class="lead">
			  <span style="position: absolute;">By</span>
			  <vs-button 
			  href="/{{question.user}}"
			  :style="{marginTop: '0px',marginLeft: '25px',fontSize: '18px',display: 'inline-block'}" transparent size="mini">
				<i class="bx bx-user"></i>&nbsp;{{question.user}}
			</vs-button>
			<span style="position: absolute;">on {{question.asked_on.date}}</span>
		</p>
		<div class="markdown-body">
			{{question.question|safe}}
		</div>
		<p style="margin-block-end: 0px;">
			{% for t in question.tags.all %}
				 <div class="badge badge-pill badge-dark" style="background-color: {{t.bg_color}};font-size:14px;">{{t.tag}}</div>
			 {% empty %}
			 <div class="badge badge-pill badge-dark">No Tags</div>
			{% endfor %}
		 </p>	
		 <vs-row>
		 <vs-button 
		 danger
		 href="/answer/{{question.url}}" :style="{fontSize: '18px'}" size="small">
			Answer
		</vs-button>
		<vs-button
		danger flat
		href="/{{question.user}}" :style="{fontSize: '18px'}" size="small">
			View Profile
		</vs-button>
		</vs-row>
		</div>
	  </div>
    </div>
    </div>
</div>
{% ifnotequal question.url "50397e64a39023ad47ac34c61ae192f0" %}
<div class="container">
	<br/>
    <h3>Answers</h3>
    {% for a in answers %}  
    <div class="card">
		<div class="card-body" style="padding: 0.75rem;">
			<div class="markdown-body">
				{{a.answer|safe|linebreaks}}
			</div>
        </div>
        <div class="card-footer" style="padding: 0.75rem;">
            <span style="font-size: 14px;">
                Answered By <a href="/{{a.answered_by}}">{{ a.answered_by }}</a> on 
                {{ a.answered_at }}
            </span>
        </div>
    </div>
    <span>&nbsp;</span>
    {% empty %}
    <h4>Nobody has answered this question yet</h4>
    {% endfor %}
</div>
</div>
{% endifnotequal %}
{% endblock %}
{% block script %}
<script>
	const app_detail = new Vue({
		el: '#app_detail',
		methods:{
		likeQuestion:  function(){
			document.querySelector('#addLike').disabled = true;
			axios.post('/like/', {
    			question: '{{question.url}}',
   				user: '{{request.user}}'
				  })
				.then((response) => {
					var liked = false
					var like_btn = document.querySelector(".bx-heart"); 
					if(like_btn === null){
						liked = true;
					}
					if(liked){
						let like_btn = document.querySelector(".bxs-heart");
						like_btn.classList.add("bx-heart");
						like_btn.classList.remove("bxs-heart");
						let likes_count = document.querySelector("#likes_count");
						likes_count.innerHTML = parseInt(likes_count.innerHTML)- 1; 
						const noti = this.$vs.notification({
							progress: 'auto',
            				sticky: true,
							color: 'dark',
							icon: '<img draggable="false" class="emoji" alt="💔" src="https://github.githubassets.com/images/icons/emoji/unicode/1f494.png" style="width: 1em; margin-left: 3px;">',
							title: 'Disliked Question {{question.title}}',
							text: `<div style="display:flex">
							<div class="vs-avatar-content 
							vs-change-color
							vs-change-color-badge" style="--vs-color:25,91,255;width:28px;height:28px">
							<div class="vs-avatar">
							<img src="{{user_profile}}" alt="">
							</div>
							</div>
							<span class="ml-1" style="margin-top: 5px">Developer - {{question.user}} lost a point 💔</span>`
						})
					}else{
						let like_btn = document.querySelector(".bx-heart");
						like_btn.classList.add("bxs-heart");
						like_btn.classList.remove("bx-heart");
						let likes_count = document.querySelector("#likes_count");
						likes_count.innerHTML = parseInt(likes_count.innerHTML) + 1
						const noti = this.$vs.notification({
							progress: 'auto',
            				sticky: true,
							color: 'dark',
							icon: `<img draggable="false" class="emoji" alt="🥳" src="https://github.githubassets.com/images/icons/emoji/unicode/1f973.png" style="width: 1em; margin-left: 3px;">`,
							title: 'Liked Question {{question.title}}',
							text: `
							<div style="display:flex">
							<div class="vs-avatar-content 
							vs-change-color
							vs-change-color-badge" style="--vs-color:25,91,255;width:28px;height:28px">
							<div class="vs-avatar">
							<img src="{{user_profile}}" alt="">
							</div>
							</div>
							<span class="ml-1" style="margin-top: 5px">Developer - {{question.user}} got +1 point 🎉</span></div>`
						})
					}
				document.querySelector('#addLike').disabled = false;
				})
				.then((error) => {
					if(error !== undefined){
						console.log(error);
					}
				})
			}
		}
	})
</script>
{% endblock %}

templates/questions/question_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block body %}
<center>
<div id="app_question_create">
<form method="POST" style="max-width: 800px;">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit"
    class="vs-button vs-button--false vs-button--size-small btn-block" style="background:rgba(var(--vs-danger));color:#fff;font-size: 18px;">
        <div class="vs-button__content">Ask a Question</div>
    </button>
</form>
</div>
</center>
{% endblock %}
{% block script %}
<script type="text/javascript">
    $(document).ready(function(){
        $('#id_tags').select2();
    });
    var app_question_create = new Vue({
        el: '#app_question_create'
    })
    const md = new SimpleMDE({
        element: document.querySelector('#id_question'),
    })
    document.querySelector('#id_question').required = "";
    document.querySelector(".CodeMirror").style.textAlign = "left";
    document.querySelector(".editor-preview-side").style.textAlign = "left";
</script>
{% endblock %}

templates/questions/question_list.html
{% extends 'base.html' %}
{% block body %}
<div id="app-trending">
{% for i in object_list %}
<div class="card mx-auto" style="max-width: 1100px;">
	<div class="card-body">
	  <h4 class="card-title font-weight-bold">{{i.title}}</h4>
	  <h4><i class="bx bxs-heart" style="color: rgba(var(--vs-danger));"></i><span style="margin-top: -1.5px;margin-left:3px;position: absolute;">{{i.likes}} Likes</span></h4>
	  <hr class="my-4">
	  <p class="lead">
		  <span style="position: absolute;">By</span>
		  <vs-button 
		  href="/{{i.user}}"
		  :style="{marginTop: '0px',marginLeft: '25px',fontSize: '18px',display: 'inline-block'}" transparent size="mini">
			<i class="bx bx-user"></i>&nbsp;{{i.user}}
		</vs-button>
		<span style="position: absolute;">{{i.asked_on.date}}</span>
	</p>
	<vs-button href="/{{i.user}}/questions/{{i.url}}" :style="{fontSize: '18px'}" size="small">
		View Question
	</vs-button>
	</div>
  </div>
  <p></p>
  {% empty %}
<h4>No Questions Asked</h4>
<h5>Ask a Question now to get it trending</h5>
<vs-button color="danger" icon="add" type="filled" href="/questions/create">
	Ask a Question
</vs-button>
{% endfor %}
</div>
{% endblock %}
{% block script %}
<script>
	const app_trending = new Vue({
		el: '#app-trending',
		data: {
		},
		delimitors: ['[[', ']]'],
	})
</script>
{% endblock %}